### ISSUE TITLE
After last cospend update "BadFunctionCallException currencyname is not a valid attribute"

### ISSUE THREAD

**Issue by iishrnika** [chenasraf/nextcloud-autocurrency#33]
BadFunctionCallException
currencyname is not a valid attribute
/lib/public/AppFramework/Db/Entity.php
Line 150
OCP\AppFramework\Db\Entity->getter()
/apps/autocurrency/lib/Service/FetchCurrenciesService.php
Line 67
OCP\AppFramework\Db\Entity->__call()
/apps/autocurrency/lib/Controller/ApiController.php
Line 97
OCA\AutoCurrency\Service\FetchCurrenciesService->fetchCurrencyRates()
/lib/private/AppFramework/Http/Dispatcher.php
Line 208
OCA\AutoCurrency\Controller\ApiController->runCron()
/lib/private/AppFramework/Http/Dispatcher.php
Line 114
OC\AppFramework\Http\Dispatcher->executeController()
/lib/private/AppFramework/App.php
Line 161
OC\AppFramework\Http\Dispatcher->dispatch()
/lib/private/Route/Router.php
Line 302
OC\AppFramework\App::main()
/ocs/v1.php
Line 43
OC\Route\Router->match()
/ocs/v2.php
Line 7
require_once("/ocs/v1.php")
Raw log entry
{
  "reqId": "REDACTED",
  "level": 3,
  "time": "REDACTED",
  "remoteAddr": "REDACTED",
  "user": "REDACTED",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/apps/autocurrency/api/cron/run",
  "message": "currencyname is not a valid attribute",
  "userAgent": "REDACTED",
  "version": "REDACTED",
  "exception": {
    "Exception": "BadFunctionCallException",
    "Message": "currencyname is not a valid attribute",
    "Code": 0,
    "Trace": [
      {
        "file": "/lib/public/AppFramework/Db/Entity.php",
        "line": 150,
        "function": "getter",
        "class": "OCP\\AppFramework\\Db\\Entity",
        "type": "->"
      },
      {
        "file": "/apps/autocurrency/lib/Service/FetchCurrenciesService.php",
        "line": 67,
        "function": "__call",
        "class": "OCP\\AppFramework\\Db\\Entity",
        "type": "->"
      },
      {
        "file": "/apps/autocurrency/lib/Controller/ApiController.php",
        "line": 97,
        "function": "fetchCurrencyRates",
        "class": "OCA\\AutoCurrency\\Service\\FetchCurrenciesService",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 208,
        "function": "runCron",
        "class": "OCA\\AutoCurrency\\Controller\\ApiController",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 114,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/ocs/v1.php",
        "line": 43,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/ocs/v2.php",
        "line": 7,
        "args": ["/ocs/v1.php"],
        "function": "require_once"
      }
    ],
    "File": "/lib/public/AppFramework/Db/Entity.php",
    "Line": 133,
    "message": "currencyname is not a valid attribute",
    "exception": [],
    "CustomMessage": "currencyname is not a valid attribute"
  },
  "id": "REDACTED"
}

**Comment by chenasraf** [comment]
Ah looks like Cospend got updated, I will make sure to release an update.

Thanks for letting me know :)

**Comment by chenasraf** [comment]
Updating App Store now, this should be fixed in v0.6.3. Please let me know if it still causes issues after the update.

If you don't see the new version on your instance yet, you might have to wait up to a day for the new version to be fetched.

**Comment by iishrnika** [comment]
Everything works fine now, thank you!
